extends Node2D


func _ready() -> void:
	SaveManager.rna = {
		"party": [
			{
				"id": "p1",
				"display_name": "기사",
				"team": "player",
				"position": Vector2i(1, 3),
				"max_hp": 60,
				"armor": 30,
				"max_ap": 2,
				"initiative": 4,
				"melee_skill": 70,
				"melee_defense": 20,
				"damage_min": 10,
				"damage_max": 18,
				"move_range": 2,
			},
			{
				"id": "p2",
				"display_name": "성직자",
				"team": "player",
				"position": Vector2i(1, 4),
				"max_hp": 40,
				"armor": 10,
				"max_ap": 2,
				"initiative": 6,
				"melee_skill": 50,
				"melee_defense": 20,
				"damage_min": 4,
				"damage_max": 8,
				"move_range": 3,
			},
			{
				"id": "p3",
				"display_name": "궁수",
				"team": "player",
				"position": Vector2i(2, 3),
				"max_hp": 30,
				"armor": 5,
				"max_ap": 2,
				"initiative": 8,
				"melee_skill": 50,
				"melee_defense": 10,
				"damage_min": 6,
				"damage_max": 12,
				"move_range": 4,
			},
		],
		"encounter": {
			"enemies": [
				{
					"id": "e1",
					"display_name": "도적",
					"team": "enemy",
					"position": Vector2i(7, 3),
					"max_hp": 30,
					"armor": 5,
					"max_ap": 2,
					"initiative": 7,
					"melee_skill": 55,
					"melee_defense": 10,
					"damage_min": 5,
					"damage_max": 10,
					"move_range": 4,
				},
				{
					"id": "e2",
					"display_name": "중갑병",
					"team": "enemy",
					"position": Vector2i(6, 4),
					"max_hp": 55,
					"armor": 25,
					"max_ap": 2,
					"initiative": 3,
					"melee_skill": 65,
					"melee_defense": 15,
					"damage_min": 8,
					"damage_max": 15,
					"move_range": 2,
				},
				{
					"id": "e3",
					"display_name": "창병",
					"team": "enemy",
					"position": Vector2i(7, 5),
					"max_hp": 35,
					"armor": 8,
					"max_ap": 2,
					"initiative": 5,
					"melee_skill": 55,
					"melee_defense": 12,
					"damage_min": 6,
					"damage_max": 11,
					"move_range": 3,
				},
			],
			"seed": 42,
		},
	}
	ScreenManager.change_screen(ScreenManager.Screen.COMBAT)
